server:
  port: 8080
  forward-headers-strategy: framework

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  thymeleaf:
    cache: false

logging:
  level:
    root: INFO

huggingface:
  apiKey: ""
  model: ""

app:
  datasource:
    laragon:
      host: ${LARAGON_DB_HOST:127.0.0.1}
      port: ${LARAGON_DB_PORT:3306}
      database: ${LARAGON_DB_NAME:caro}
      username: ${LARAGON_DB_USER:root}
      password: ${LARAGON_DB_PASS:}
  websocket:
    allowed-origin-patterns: ${WS_ALLOWED_ORIGINS:*}
